# Generated by Django 3.1.3 on 2020-11-10 12:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('classyeveryday', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='ref_code',
            new_name='order_id',
        ),
    ]
