# Generated by Django 3.1.3 on 2020-11-11 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classyeveryday', '0004_contact'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='email',
            field=models.EmailField(max_length=50),
        ),
    ]
