# Generated by Django 3.1.3 on 2020-11-12 09:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('classyeveryday', '0006_images'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='images',
            name='item',
        ),
        migrations.AddField(
            model_name='item',
            name='images',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='classyeveryday.images'),
        ),
    ]
