# Generated by Django 3.1.3 on 2020-11-12 09:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('classyeveryday', '0007_auto_20201112_1441'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='images',
        ),
        migrations.DeleteModel(
            name='Images',
        ),
    ]
