# Generated by Django 3.1.3 on 2020-11-12 10:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('classyeveryday', '0008_auto_20201112_1505'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='available_size',
        ),
        migrations.CreateModel(
            name='Variation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('size', models.CharField(choices=[('XS', 'Xtra Small'), ('S', 'Small'), ('M', 'Medium'), ('L', 'Large'), ('XL', 'Xtra Large')], max_length=120)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='classyeveryday.item')),
            ],
        ),
    ]
