# Generated by Django 3.1.3 on 2020-11-12 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classyeveryday', '0010_auto_20201112_1708'),
    ]

    operations = [
        migrations.AddField(
            model_name='address',
            name='order_id',
            field=models.CharField(default=7666677, max_length=20),
            preserve_default=False,
        ),
    ]
