# Generated by Django 3.1.3 on 2020-11-20 18:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('classyeveryday', '0011_address_order_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='multipleImages',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('images', models.FileField(upload_to='')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='classyeveryday.item')),
            ],
        ),
    ]
