# Generated by Django 3.1.3 on 2021-10-01 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classyeveryday', '0012_multipleimages'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='one_click_purchasing',
            new_name='is_verified',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='stripe_customer_id',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='auth_token',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
