# Generated by Django 3.1.3 on 2021-10-02 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classyeveryday', '0013_auto_20211001_1416'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='stock',
            field=models.CharField(choices=[('IN', 'IN'), ('OUT', 'OUT')], default='IN', max_length=10),
        ),
    ]
